autoload -U promptinit; promptinit;

alias code="code-insiders"
alias a="php artisan"
alias g="git"

export PATH="$PATH:/home/taavi/bin:/home/taavi/.local/bin"

source <(antibody init)
antibody bundle < ~taavi/src/dotfiles/zsh/zsh_plugins.txt

source <(gh completion -s zsh)

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
