#!/usr/bin/env zsh
# https://github.com/supertassu/dotfiles
# .zshrc

autoload -U promptinit; promptinit;

source <(antibody init)
antibody bundle < ~/dotfiles/zsh/zsh_plugins.txt

export PATH="$HOME/dotfiles/bin:$HOME/.cargo/bin:$HOME/.yarn/bin:/snap/bin:./node_modules/.bin:$PATH"

[[ cmd_exists("hub") ]] && eval "$(hub alias -s)"
[[ cmd_exists("thefuck") ]] && eval "$(thefuck --alias)"

alias vim="nvim"
[[ cmd_exists("vtop") ]] && alias top="vtop"
[[ cmd_exists("exa") ]] && alias ls="exa"
[[ cmd_exists("exa") ]] && alias tree="exa --tree"
[[ cmd_exists("bat") ]] && alias cat="bat"
alias dc="docker-compose"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export VISUAL=nvim
export EDITOR="$VISUAL"
